# Generated by Django 3.0.5 on 2023-02-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Brand_Contact',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_Logo',
            field=models.ImageField(upload_to='uploads/brands-logo'),
        ),
    ]
