# Generated by Django 3.0.5 on 2023-02-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_baseproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseproduct',
            old_name='BrandID',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='baseproduct',
            old_name='CategoryID',
            new_name='category',
        ),
    ]
