# Generated by Django 3.0.5 on 2023-02-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_flavour_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveSmallIntegerField()),
                ('mrp', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BaseProduct')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Flavour')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Quantity')),
            ],
        ),
    ]
