# Generated by Django 3.0.5 on 2023-03-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_brand_brand_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/product-images')),
                ('img_type', models.CharField(choices=[('Face', 'Face'), ('Info', 'Info'), ('other', 'other')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductV')),
            ],
        ),
    ]
