# Generated by Django 3.0.5 on 2023-04-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mrp', models.PositiveSmallIntegerField()),
                ('selling_price', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Flavour')),
                ('qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='productv',
            name='base_product',
        ),
        migrations.RemoveField(
            model_name='productv',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='productv',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='BaseProduct',
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.DeleteModel(
            name='ProductV',
        ),
    ]
