# Generated by Django 3.0.5 on 2023-04-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230405_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='prod_name',
        ),
    ]
