# Generated by Django 3.0.5 on 2023-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230414_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='uploads/product-images/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
