# Generated by Django 3.0.5 on 2023-05-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230521_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Customer',
        ),
    ]
